//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-filter_department_service-SSD_SERVICE_ID_sd_kxabzJtnUwVxiUP5
import { filter_department_service as SSD_SERVICE_ID_sd_kxabzJtnUwVxiUP5 } from './sd-services/department/filter_department/filter_department_service';
//CORE_REFERENCE_IMPORT-filter_department_api-SSD_SERVICE_ID_sd_7PvugXUXmRHa3g0m
import { filter_department_api as SSD_SERVICE_ID_sd_7PvugXUXmRHa3g0m } from './sd-services/department/filter_department/filter_department_api';
//CORE_REFERENCE_IMPORT-find_a_department_service-SSD_SERVICE_ID_sd_n5PTUHI2gkktQUCx
import { find_a_department_service as SSD_SERVICE_ID_sd_n5PTUHI2gkktQUCx } from './sd-services/department/find_all_department/find_a_department_service';
//CORE_REFERENCE_IMPORT-find_a_department_api-SSD_SERVICE_ID_sd_xLrnXFScfMeieUY4
import { find_a_department_api as SSD_SERVICE_ID_sd_xLrnXFScfMeieUY4 } from './sd-services/department/find_all_department/find_a_department_api';
//CORE_REFERENCE_IMPORT-token_by_date_service-SSD_SERVICE_ID_sd_lRLqUDOgTWLPHbfo
import { token_by_date_service as SSD_SERVICE_ID_sd_lRLqUDOgTWLPHbfo } from './sd-services/appointments/token_by_date/token_by_date_service';
//CORE_REFERENCE_IMPORT-token_by_date_api-SSD_SERVICE_ID_sd_qI1FgEF5Qg6Su2HR
import { token_by_date_api as SSD_SERVICE_ID_sd_qI1FgEF5Qg6Su2HR } from './sd-services/appointments/token_by_date/token_by_date_api';
//CORE_REFERENCE_IMPORT-update_appointment_status_service-SSD_SERVICE_ID_sd_F8uRJxFxyYnAocyM
import { update_appointment_status_service as SSD_SERVICE_ID_sd_F8uRJxFxyYnAocyM } from './sd-services/appointments/update_appointment_status/update_appointment_status_service';
//CORE_REFERENCE_IMPORT-update_appointment_status_api-SSD_SERVICE_ID_sd_ADMaiDiZnUmK75yJ
import { update_appointment_status_api as SSD_SERVICE_ID_sd_ADMaiDiZnUmK75yJ } from './sd-services/appointments/update_appointment_status/update_appointment_status_api';
//CORE_REFERENCE_IMPORT-create_appointment_service-SSD_SERVICE_ID_sd_Fm1xxqvPxjmjZV2a
import { create_appointment_service as SSD_SERVICE_ID_sd_Fm1xxqvPxjmjZV2a } from './sd-services/appointments/create_appointment/create_appointment_service';
//CORE_REFERENCE_IMPORT-create_appointment_api-SSD_SERVICE_ID_sd_jDuq1BS2qjRBiMaU
import { create_appointment_api as SSD_SERVICE_ID_sd_jDuq1BS2qjRBiMaU } from './sd-services/appointments/create_appointment/create_appointment_api';
//CORE_REFERENCE_IMPORT-find_user_by_phone_service-SSD_SERVICE_ID_sd_mo0SqSSi7ZxTtxA6
import { find_user_by_phone_service as SSD_SERVICE_ID_sd_mo0SqSSi7ZxTtxA6 } from './sd-services/users/find_user_by_phone/find_user_by_phone_service';
//CORE_REFERENCE_IMPORT-find_user_by_phone_api-SSD_SERVICE_ID_sd_7LQCD4yAtImzsIhC
import { find_user_by_phone_api as SSD_SERVICE_ID_sd_7LQCD4yAtImzsIhC } from './sd-services/users/find_user_by_phone/find_user_by_phone_api';
//CORE_REFERENCE_IMPORT-find_user_by_id_service-SSD_SERVICE_ID_sd_er58WUWxKEh6IEiD
import { find_user_by_id_service as SSD_SERVICE_ID_sd_er58WUWxKEh6IEiD } from './sd-services/users/find_user_by_id/find_user_by_id_service';
//CORE_REFERENCE_IMPORT-find_user_by_id_api-SSD_SERVICE_ID_sd_OlWygWOlSGOizS9A
import { find_user_by_id_api as SSD_SERVICE_ID_sd_OlWygWOlSGOizS9A } from './sd-services/users/find_user_by_id/find_user_by_id_api';
//CORE_REFERENCE_IMPORT-create_user_service-SSD_SERVICE_ID_sd_1utwBDtR9iw7QRXa
import { create_user_service as SSD_SERVICE_ID_sd_1utwBDtR9iw7QRXa } from './sd-services/users/create_user/create_user_service';
//CORE_REFERENCE_IMPORT-create_user_api-SSD_SERVICE_ID_sd_UvhLjLBfo8HXDZJS
import { create_user_api as SSD_SERVICE_ID_sd_UvhLjLBfo8HXDZJS } from './sd-services/users/create_user/create_user_api';
//CORE_REFERENCE_IMPORT-update_doctor_service-SSD_SERVICE_ID_sd_mhuKmoTwxVKclwNX
import { update_doctor_service as SSD_SERVICE_ID_sd_mhuKmoTwxVKclwNX } from './sd-services/doctors/update_doctor/update_doctor_service';
//CORE_REFERENCE_IMPORT-update_doctor_api-SSD_SERVICE_ID_sd_hyeC8CsVYrjg7rox
import { update_doctor_api as SSD_SERVICE_ID_sd_hyeC8CsVYrjg7rox } from './sd-services/doctors/update_doctor/update_doctor_api';
//CORE_REFERENCE_IMPORT-find_all_doctor_service-SSD_SERVICE_ID_sd_FdlVrRt9r82JaAwS
import { find_all_doctor_service as SSD_SERVICE_ID_sd_FdlVrRt9r82JaAwS } from './sd-services/doctors/find_all_doctor/find_all_doctor_service';
//CORE_REFERENCE_IMPORT-find_all_doctor_api-SSD_SERVICE_ID_sd_WN1cwNteT7XRlirY
import { find_all_doctor_api as SSD_SERVICE_ID_sd_WN1cwNteT7XRlirY } from './sd-services/doctors/find_all_doctor/find_all_doctor_api';
//CORE_REFERENCE_IMPORT-find_doctor_by_department_service-SSD_SERVICE_ID_sd_g9fifOjKOOcCuPU4
import { find_doctor_by_department_service as SSD_SERVICE_ID_sd_g9fifOjKOOcCuPU4 } from './sd-services/doctors/find_doctor_by_department/find_doctor_by_department_service';
//CORE_REFERENCE_IMPORT-find_doctor_by_department_api-SSD_SERVICE_ID_sd_BD0aT7xadKpR7xba
import { find_doctor_by_department_api as SSD_SERVICE_ID_sd_BD0aT7xadKpR7xba } from './sd-services/doctors/find_doctor_by_department/find_doctor_by_department_api';
//CORE_REFERENCE_IMPORT-find_a_doctor_service-SSD_SERVICE_ID_sd_yKj2YERnp5ndUcCA
import { find_a_doctor_service as SSD_SERVICE_ID_sd_yKj2YERnp5ndUcCA } from './sd-services/doctors/find_a_doctor/find_a_doctor_service';
//CORE_REFERENCE_IMPORT-find_a_doctor_api-SSD_SERVICE_ID_sd_pmjvulYuDTz2YoGU
import { find_a_doctor_api as SSD_SERVICE_ID_sd_pmjvulYuDTz2YoGU } from './sd-services/doctors/find_a_doctor/find_a_doctor_api';
//CORE_REFERENCE_IMPORT-create_doctor_service-SSD_SERVICE_ID_sd_45JgZ7OwsjvEYUcg
import { create_doctor_service as SSD_SERVICE_ID_sd_45JgZ7OwsjvEYUcg } from './sd-services/doctors/create_doctor/create_doctor_service';
//CORE_REFERENCE_IMPORT-create_doctor_api-SSD_SERVICE_ID_sd_XiO53B7Cd7Fbrhn3
import { create_doctor_api as SSD_SERVICE_ID_sd_XiO53B7Cd7Fbrhn3 } from './sd-services/doctors/create_doctor/create_doctor_api';
//CORE_REFERENCE_IMPORT-update_department_service-SSD_SERVICE_ID_sd_9d3akMmIsei4wjRS
import { update_department_service as SSD_SERVICE_ID_sd_9d3akMmIsei4wjRS } from './sd-services/department/update_department/update_department_service';
//CORE_REFERENCE_IMPORT-update_department_api-SSD_SERVICE_ID_sd_OnBEHsyGSJtuYIHJ
import { update_department_api as SSD_SERVICE_ID_sd_OnBEHsyGSJtuYIHJ } from './sd-services/department/update_department/update_department_api';
//CORE_REFERENCE_IMPORT-create_department_service-SSD_SERVICE_ID_sd_7wo0dUAyZGNCRTQn
import { create_department_service as SSD_SERVICE_ID_sd_7wo0dUAyZGNCRTQn } from './sd-services/department/create_department/create_department_service';
//CORE_REFERENCE_IMPORT-create_department_api-SSD_SERVICE_ID_sd_gphBUqeiZIyZQsAq
import { create_department_api as SSD_SERVICE_ID_sd_gphBUqeiZIyZQsAq } from './sd-services/department/create_department/create_department_api';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-filter_department_service-SSD_SERVICE_ID_sd_kxabzJtnUwVxiUP5
SSD_SERVICE_ID_sd_kxabzJtnUwVxiUP5,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-filter_department_api-SSD_SERVICE_ID_sd_7PvugXUXmRHa3g0m
SSD_SERVICE_ID_sd_7PvugXUXmRHa3g0m,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_a_department_service-SSD_SERVICE_ID_sd_n5PTUHI2gkktQUCx
SSD_SERVICE_ID_sd_n5PTUHI2gkktQUCx,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_a_department_api-SSD_SERVICE_ID_sd_xLrnXFScfMeieUY4
SSD_SERVICE_ID_sd_xLrnXFScfMeieUY4,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-token_by_date_service-SSD_SERVICE_ID_sd_lRLqUDOgTWLPHbfo
SSD_SERVICE_ID_sd_lRLqUDOgTWLPHbfo,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-token_by_date_api-SSD_SERVICE_ID_sd_qI1FgEF5Qg6Su2HR
SSD_SERVICE_ID_sd_qI1FgEF5Qg6Su2HR,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_appointment_status_service-SSD_SERVICE_ID_sd_F8uRJxFxyYnAocyM
SSD_SERVICE_ID_sd_F8uRJxFxyYnAocyM,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_appointment_status_api-SSD_SERVICE_ID_sd_ADMaiDiZnUmK75yJ
SSD_SERVICE_ID_sd_ADMaiDiZnUmK75yJ,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_appointment_service-SSD_SERVICE_ID_sd_Fm1xxqvPxjmjZV2a
SSD_SERVICE_ID_sd_Fm1xxqvPxjmjZV2a,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_appointment_api-SSD_SERVICE_ID_sd_jDuq1BS2qjRBiMaU
SSD_SERVICE_ID_sd_jDuq1BS2qjRBiMaU,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_user_by_phone_service-SSD_SERVICE_ID_sd_mo0SqSSi7ZxTtxA6
SSD_SERVICE_ID_sd_mo0SqSSi7ZxTtxA6,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_user_by_phone_api-SSD_SERVICE_ID_sd_7LQCD4yAtImzsIhC
SSD_SERVICE_ID_sd_7LQCD4yAtImzsIhC,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_user_by_id_service-SSD_SERVICE_ID_sd_er58WUWxKEh6IEiD
SSD_SERVICE_ID_sd_er58WUWxKEh6IEiD,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_user_by_id_api-SSD_SERVICE_ID_sd_OlWygWOlSGOizS9A
SSD_SERVICE_ID_sd_OlWygWOlSGOizS9A,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_user_service-SSD_SERVICE_ID_sd_1utwBDtR9iw7QRXa
SSD_SERVICE_ID_sd_1utwBDtR9iw7QRXa,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_user_api-SSD_SERVICE_ID_sd_UvhLjLBfo8HXDZJS
SSD_SERVICE_ID_sd_UvhLjLBfo8HXDZJS,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_doctor_service-SSD_SERVICE_ID_sd_mhuKmoTwxVKclwNX
SSD_SERVICE_ID_sd_mhuKmoTwxVKclwNX,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_doctor_api-SSD_SERVICE_ID_sd_hyeC8CsVYrjg7rox
SSD_SERVICE_ID_sd_hyeC8CsVYrjg7rox,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_all_doctor_service-SSD_SERVICE_ID_sd_FdlVrRt9r82JaAwS
SSD_SERVICE_ID_sd_FdlVrRt9r82JaAwS,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_all_doctor_api-SSD_SERVICE_ID_sd_WN1cwNteT7XRlirY
SSD_SERVICE_ID_sd_WN1cwNteT7XRlirY,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_doctor_by_department_service-SSD_SERVICE_ID_sd_g9fifOjKOOcCuPU4
SSD_SERVICE_ID_sd_g9fifOjKOOcCuPU4,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_doctor_by_department_api-SSD_SERVICE_ID_sd_BD0aT7xadKpR7xba
SSD_SERVICE_ID_sd_BD0aT7xadKpR7xba,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_a_doctor_service-SSD_SERVICE_ID_sd_yKj2YERnp5ndUcCA
SSD_SERVICE_ID_sd_yKj2YERnp5ndUcCA,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-find_a_doctor_api-SSD_SERVICE_ID_sd_pmjvulYuDTz2YoGU
SSD_SERVICE_ID_sd_pmjvulYuDTz2YoGU,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_doctor_service-SSD_SERVICE_ID_sd_45JgZ7OwsjvEYUcg
SSD_SERVICE_ID_sd_45JgZ7OwsjvEYUcg,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_doctor_api-SSD_SERVICE_ID_sd_XiO53B7Cd7Fbrhn3
SSD_SERVICE_ID_sd_XiO53B7Cd7Fbrhn3,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_department_service-SSD_SERVICE_ID_sd_9d3akMmIsei4wjRS
SSD_SERVICE_ID_sd_9d3akMmIsei4wjRS,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_department_api-SSD_SERVICE_ID_sd_OnBEHsyGSJtuYIHJ
SSD_SERVICE_ID_sd_OnBEHsyGSJtuYIHJ,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_department_service-SSD_SERVICE_ID_sd_7wo0dUAyZGNCRTQn
SSD_SERVICE_ID_sd_7wo0dUAyZGNCRTQn,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_department_api-SSD_SERVICE_ID_sd_gphBUqeiZIyZQsAq
SSD_SERVICE_ID_sd_gphBUqeiZIyZQsAq,
];
