//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-getHolidaysService-SSD_SERVICE_ID_sd_YQsrEeWXyNrlkzy2
import { getHolidaysService as SSD_SERVICE_ID_sd_YQsrEeWXyNrlkzy2 } from './sd-services/holidays/getHolidays/getHolidaysService';
//CORE_REFERENCE_IMPORT-getHolidaysApi-SSD_SERVICE_ID_sd_OuQVJCoggX0aNlA9
import { getHolidaysApi as SSD_SERVICE_ID_sd_OuQVJCoggX0aNlA9 } from './sd-services/holidays/getHolidays/getHolidaysApi';
//CORE_REFERENCE_IMPORT-addHolidaysService-SSD_SERVICE_ID_sd_Z1cnyfcmgp7odfpP
import { addHolidaysService as SSD_SERVICE_ID_sd_Z1cnyfcmgp7odfpP } from './sd-services/holidays/addHolidays/addHolidaysService';
//CORE_REFERENCE_IMPORT-addHolidaysApi-SSD_SERVICE_ID_sd_Zcqf1QAleVhvLaS6
import { addHolidaysApi as SSD_SERVICE_ID_sd_Zcqf1QAleVhvLaS6 } from './sd-services/holidays/addHolidays/addHolidaysApi';
//CORE_REFERENCE_IMPORT-deleteholidayService-SSD_SERVICE_ID_sd_u54J74Bt7KK7No30
import { deleteholidayService as SSD_SERVICE_ID_sd_u54J74Bt7KK7No30 } from './sd-services/holidays/deleteHolidays/deleteholidayService';
//CORE_REFERENCE_IMPORT-deleteHolidayApi-SSD_SERVICE_ID_sd_5HTHp6toKWteyttX
import { deleteHolidayApi as SSD_SERVICE_ID_sd_5HTHp6toKWteyttX } from './sd-services/holidays/deleteHolidays/deleteHolidayApi';
//CORE_REFERENCE_IMPORT-updateHolidaysService-SSD_SERVICE_ID_sd_CMgNkPiuQLSMYrJE
import { updateHolidaysService as SSD_SERVICE_ID_sd_CMgNkPiuQLSMYrJE } from './sd-services/holidays/updateHolidays/updateHolidaysService';
//CORE_REFERENCE_IMPORT-updateHolidaysApi-SSD_SERVICE_ID_sd_O56mCG7Vk1hZBjdl
import { updateHolidaysApi as SSD_SERVICE_ID_sd_O56mCG7Vk1hZBjdl } from './sd-services/holidays/updateHolidays/updateHolidaysApi';
//CORE_REFERENCE_IMPORT-filterservice-SSD_SERVICE_ID_sd_YH9aqPJ68KAnCtkB
import { filterservice as SSD_SERVICE_ID_sd_YH9aqPJ68KAnCtkB } from './sd-services/filter/filterservice';
//CORE_REFERENCE_IMPORT-upload_api-SSD_SERVICE_ID_sd_ob3CnQ0ND87WDPUG
import { upload_api as SSD_SERVICE_ID_sd_ob3CnQ0ND87WDPUG } from './sd-services/pdf/upload_api';
//CORE_REFERENCE_IMPORT-upload_service-SSD_SERVICE_ID_sd_sebhAvpyjJHu1R1Z
import { upload_service as SSD_SERVICE_ID_sd_sebhAvpyjJHu1R1Z } from './sd-services/pdf/upload_service';
//CORE_REFERENCE_IMPORT-auto_doctor_service-SSD_SERVICE_ID_sd_bthY8bjd638CxsCf
import { auto_doctor_service as SSD_SERVICE_ID_sd_bthY8bjd638CxsCf } from './sd-services/common/auto_doctor_select/auto_doctor_service';
//CORE_REFERENCE_IMPORT-auto_doctor_api-SSD_SERVICE_ID_sd_ta2UPnAaBavHfvQ8
import { auto_doctor_api as SSD_SERVICE_ID_sd_ta2UPnAaBavHfvQ8 } from './sd-services/common/auto_doctor_select/auto_doctor_api';
//CORE_REFERENCE_IMPORT-payement_verified_service-SSD_SERVICE_ID_sd_tjA7Kxv8OylO0nnh
import { payement_verified_service as SSD_SERVICE_ID_sd_tjA7Kxv8OylO0nnh } from './sd-services/common/payment_verified/payement_verified_service';
//CORE_REFERENCE_IMPORT-payment_verified_api-SSD_SERVICE_ID_sd_jPPvsFExUCTPJE88
import { payment_verified_api as SSD_SERVICE_ID_sd_jPPvsFExUCTPJE88 } from './sd-services/common/payment_verified/payment_verified_api';
//CORE_REFERENCE_IMPORT-payment_cash_service-SSD_SERVICE_ID_sd_l5yYyef8zSJYH0UY
import { payment_cash_service as SSD_SERVICE_ID_sd_l5yYyef8zSJYH0UY } from './sd-services/common/payment_req/payment_cash_service';
//CORE_REFERENCE_IMPORT-payment_service-SSD_SERVICE_ID_sd_jfya9jPAl3GjcYYn
import { payment_service as SSD_SERVICE_ID_sd_jfya9jPAl3GjcYYn } from './sd-services/common/payment_req/payment_service';
//CORE_REFERENCE_IMPORT-payment_api-SSD_SERVICE_ID_sd_5uKBgMCMEY9EmeOD
import { payment_api as SSD_SERVICE_ID_sd_5uKBgMCMEY9EmeOD } from './sd-services/common/payment_req/payment_api';
//CORE_REFERENCE_IMPORT-create_payment_service-SSD_SERVICE_ID_sd_WDoX05PyLP0zXvOd
import { create_payment_service as SSD_SERVICE_ID_sd_WDoX05PyLP0zXvOd } from './sd-services/payment/create_payment/create_payment_service';
//CORE_REFERENCE_IMPORT-get_appointment_flow-SSD_SERVICE_ID_sd_r0H8vsrn1p2lt1Ok
import { get_appointment_flow as SSD_SERVICE_ID_sd_r0H8vsrn1p2lt1Ok } from './sd-services/common/get_appointments/get_appointment_flow';
//CORE_REFERENCE_IMPORT-get_appointment_api-SSD_SERVICE_ID_sd_s7Dqt2H83bRphca8
import { get_appointment_api as SSD_SERVICE_ID_sd_s7Dqt2H83bRphca8 } from './sd-services/common/get_appointments/get_appointment_api';
//CORE_REFERENCE_IMPORT-appointment_api-SSD_SERVICE_ID_sd_xBgpGrAxrMfgsKKs
import { appointment_api as SSD_SERVICE_ID_sd_xBgpGrAxrMfgsKKs } from './sd-services/common/create_appointment/appointment_api';
//CORE_REFERENCE_IMPORT-appointment_service-SSD_SERVICE_ID_sd_eBuPhijos3M7fnVJ
import { appointment_service as SSD_SERVICE_ID_sd_eBuPhijos3M7fnVJ } from './sd-services/common/create_appointment/appointment_service';
//CORE_REFERENCE_IMPORT-filter_doctor_api-SSD_SERVICE_ID_sd_WN1cwNteT7XRlirY
import { filter_doctor_api as SSD_SERVICE_ID_sd_WN1cwNteT7XRlirY } from './sd-services/doctors/filter_doctor/filter_doctor_api';
//CORE_REFERENCE_IMPORT-filter_department_api-SSD_SERVICE_ID_sd_7PvugXUXmRHa3g0m
import { filter_department_api as SSD_SERVICE_ID_sd_7PvugXUXmRHa3g0m } from './sd-services/department/filter_department/filter_department_api';
//CORE_REFERENCE_IMPORT-update_appointment_status_service-SSD_SERVICE_ID_sd_F8uRJxFxyYnAocyM
import { update_appointment_status_service as SSD_SERVICE_ID_sd_F8uRJxFxyYnAocyM } from './sd-services/appointments/update_appointment_status/update_appointment_status_service';
//CORE_REFERENCE_IMPORT-update_appointment_status_api-SSD_SERVICE_ID_sd_ADMaiDiZnUmK75yJ
import { update_appointment_status_api as SSD_SERVICE_ID_sd_ADMaiDiZnUmK75yJ } from './sd-services/appointments/update_appointment_status/update_appointment_status_api';
//CORE_REFERENCE_IMPORT-create_appointment_service-SSD_SERVICE_ID_sd_Fm1xxqvPxjmjZV2a
import { create_appointment_service as SSD_SERVICE_ID_sd_Fm1xxqvPxjmjZV2a } from './sd-services/appointments/create_appointment/create_appointment_service';
//CORE_REFERENCE_IMPORT-create_user_service-SSD_SERVICE_ID_sd_1utwBDtR9iw7QRXa
import { create_user_service as SSD_SERVICE_ID_sd_1utwBDtR9iw7QRXa } from './sd-services/users/create_user/create_user_service';
//CORE_REFERENCE_IMPORT-update_doctor_service-SSD_SERVICE_ID_sd_mhuKmoTwxVKclwNX
import { update_doctor_service as SSD_SERVICE_ID_sd_mhuKmoTwxVKclwNX } from './sd-services/doctors/update_doctor/update_doctor_service';
//CORE_REFERENCE_IMPORT-update_doctor_api-SSD_SERVICE_ID_sd_hyeC8CsVYrjg7rox
import { update_doctor_api as SSD_SERVICE_ID_sd_hyeC8CsVYrjg7rox } from './sd-services/doctors/update_doctor/update_doctor_api';
//CORE_REFERENCE_IMPORT-create_doctor_service-SSD_SERVICE_ID_sd_45JgZ7OwsjvEYUcg
import { create_doctor_service as SSD_SERVICE_ID_sd_45JgZ7OwsjvEYUcg } from './sd-services/doctors/create_doctor/create_doctor_service';
//CORE_REFERENCE_IMPORT-create_doctor_api-SSD_SERVICE_ID_sd_XiO53B7Cd7Fbrhn3
import { create_doctor_api as SSD_SERVICE_ID_sd_XiO53B7Cd7Fbrhn3 } from './sd-services/doctors/create_doctor/create_doctor_api';
//CORE_REFERENCE_IMPORT-update_department_service-SSD_SERVICE_ID_sd_9d3akMmIsei4wjRS
import { update_department_service as SSD_SERVICE_ID_sd_9d3akMmIsei4wjRS } from './sd-services/department/update_department/update_department_service';
//CORE_REFERENCE_IMPORT-update_department_api-SSD_SERVICE_ID_sd_OnBEHsyGSJtuYIHJ
import { update_department_api as SSD_SERVICE_ID_sd_OnBEHsyGSJtuYIHJ } from './sd-services/department/update_department/update_department_api';
//CORE_REFERENCE_IMPORT-create_department_service-SSD_SERVICE_ID_sd_7wo0dUAyZGNCRTQn
import { create_department_service as SSD_SERVICE_ID_sd_7wo0dUAyZGNCRTQn } from './sd-services/department/create_department/create_department_service';
//CORE_REFERENCE_IMPORT-create_department_api-SSD_SERVICE_ID_sd_gphBUqeiZIyZQsAq
import { create_department_api as SSD_SERVICE_ID_sd_gphBUqeiZIyZQsAq } from './sd-services/department/create_department/create_department_api';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-getHolidaysService-SSD_SERVICE_ID_sd_YQsrEeWXyNrlkzy2
SSD_SERVICE_ID_sd_YQsrEeWXyNrlkzy2,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-getHolidaysApi-SSD_SERVICE_ID_sd_OuQVJCoggX0aNlA9
SSD_SERVICE_ID_sd_OuQVJCoggX0aNlA9,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-addHolidaysService-SSD_SERVICE_ID_sd_Z1cnyfcmgp7odfpP
SSD_SERVICE_ID_sd_Z1cnyfcmgp7odfpP,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-addHolidaysApi-SSD_SERVICE_ID_sd_Zcqf1QAleVhvLaS6
SSD_SERVICE_ID_sd_Zcqf1QAleVhvLaS6,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-deleteholidayService-SSD_SERVICE_ID_sd_u54J74Bt7KK7No30
SSD_SERVICE_ID_sd_u54J74Bt7KK7No30,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-deleteHolidayApi-SSD_SERVICE_ID_sd_5HTHp6toKWteyttX
SSD_SERVICE_ID_sd_5HTHp6toKWteyttX,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateHolidaysService-SSD_SERVICE_ID_sd_CMgNkPiuQLSMYrJE
SSD_SERVICE_ID_sd_CMgNkPiuQLSMYrJE,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateHolidaysApi-SSD_SERVICE_ID_sd_O56mCG7Vk1hZBjdl
SSD_SERVICE_ID_sd_O56mCG7Vk1hZBjdl,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-filterservice-SSD_SERVICE_ID_sd_YH9aqPJ68KAnCtkB
SSD_SERVICE_ID_sd_YH9aqPJ68KAnCtkB,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-upload_api-SSD_SERVICE_ID_sd_ob3CnQ0ND87WDPUG
SSD_SERVICE_ID_sd_ob3CnQ0ND87WDPUG,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-upload_service-SSD_SERVICE_ID_sd_sebhAvpyjJHu1R1Z
SSD_SERVICE_ID_sd_sebhAvpyjJHu1R1Z,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-auto_doctor_service-SSD_SERVICE_ID_sd_bthY8bjd638CxsCf
SSD_SERVICE_ID_sd_bthY8bjd638CxsCf,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-auto_doctor_api-SSD_SERVICE_ID_sd_ta2UPnAaBavHfvQ8
SSD_SERVICE_ID_sd_ta2UPnAaBavHfvQ8,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-payement_verified_service-SSD_SERVICE_ID_sd_tjA7Kxv8OylO0nnh
SSD_SERVICE_ID_sd_tjA7Kxv8OylO0nnh,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-payment_verified_api-SSD_SERVICE_ID_sd_jPPvsFExUCTPJE88
SSD_SERVICE_ID_sd_jPPvsFExUCTPJE88,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-payment_cash_service-SSD_SERVICE_ID_sd_l5yYyef8zSJYH0UY
SSD_SERVICE_ID_sd_l5yYyef8zSJYH0UY,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-payment_service-SSD_SERVICE_ID_sd_jfya9jPAl3GjcYYn
SSD_SERVICE_ID_sd_jfya9jPAl3GjcYYn,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-payment_api-SSD_SERVICE_ID_sd_5uKBgMCMEY9EmeOD
SSD_SERVICE_ID_sd_5uKBgMCMEY9EmeOD,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_payment_service-SSD_SERVICE_ID_sd_WDoX05PyLP0zXvOd
SSD_SERVICE_ID_sd_WDoX05PyLP0zXvOd,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-get_appointment_flow-SSD_SERVICE_ID_sd_r0H8vsrn1p2lt1Ok
SSD_SERVICE_ID_sd_r0H8vsrn1p2lt1Ok,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-get_appointment_api-SSD_SERVICE_ID_sd_s7Dqt2H83bRphca8
SSD_SERVICE_ID_sd_s7Dqt2H83bRphca8,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-appointment_api-SSD_SERVICE_ID_sd_xBgpGrAxrMfgsKKs
SSD_SERVICE_ID_sd_xBgpGrAxrMfgsKKs,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-appointment_service-SSD_SERVICE_ID_sd_eBuPhijos3M7fnVJ
SSD_SERVICE_ID_sd_eBuPhijos3M7fnVJ,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-filter_doctor_api-SSD_SERVICE_ID_sd_WN1cwNteT7XRlirY
SSD_SERVICE_ID_sd_WN1cwNteT7XRlirY,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-filter_department_api-SSD_SERVICE_ID_sd_7PvugXUXmRHa3g0m
SSD_SERVICE_ID_sd_7PvugXUXmRHa3g0m,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_appointment_status_service-SSD_SERVICE_ID_sd_F8uRJxFxyYnAocyM
SSD_SERVICE_ID_sd_F8uRJxFxyYnAocyM,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_appointment_status_api-SSD_SERVICE_ID_sd_ADMaiDiZnUmK75yJ
SSD_SERVICE_ID_sd_ADMaiDiZnUmK75yJ,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_appointment_service-SSD_SERVICE_ID_sd_Fm1xxqvPxjmjZV2a
SSD_SERVICE_ID_sd_Fm1xxqvPxjmjZV2a,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_user_service-SSD_SERVICE_ID_sd_1utwBDtR9iw7QRXa
SSD_SERVICE_ID_sd_1utwBDtR9iw7QRXa,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_doctor_service-SSD_SERVICE_ID_sd_mhuKmoTwxVKclwNX
SSD_SERVICE_ID_sd_mhuKmoTwxVKclwNX,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_doctor_api-SSD_SERVICE_ID_sd_hyeC8CsVYrjg7rox
SSD_SERVICE_ID_sd_hyeC8CsVYrjg7rox,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_doctor_service-SSD_SERVICE_ID_sd_45JgZ7OwsjvEYUcg
SSD_SERVICE_ID_sd_45JgZ7OwsjvEYUcg,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_doctor_api-SSD_SERVICE_ID_sd_XiO53B7Cd7Fbrhn3
SSD_SERVICE_ID_sd_XiO53B7Cd7Fbrhn3,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_department_service-SSD_SERVICE_ID_sd_9d3akMmIsei4wjRS
SSD_SERVICE_ID_sd_9d3akMmIsei4wjRS,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_department_api-SSD_SERVICE_ID_sd_OnBEHsyGSJtuYIHJ
SSD_SERVICE_ID_sd_OnBEHsyGSJtuYIHJ,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_department_service-SSD_SERVICE_ID_sd_7wo0dUAyZGNCRTQn
SSD_SERVICE_ID_sd_7wo0dUAyZGNCRTQn,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-create_department_api-SSD_SERVICE_ID_sd_gphBUqeiZIyZQsAq
SSD_SERVICE_ID_sd_gphBUqeiZIyZQsAq,
];
